services:
  app:
    build:
      dockerfile: ./Dockerfile
    env_file: .env
    ports:
      - "3000:3000"
    volumes:
      - app-data:/data
    environment:
      DATA_DIR: /data
      DATABASE_CLIENT: sqlite
      DATABASE_FILENAME: /data/database.sqlite
    restart: unless-stopped

volumes:
  app-data:
